Parameters:
    Project:
      Description: Project Name | WebSite name 
      Type: String

Resources:
    Website:
      Type: AWS::CloudFormation::Stack
      Properties:
          Parameters:
            Project: !Ref Project
          TemplateURL: ./stacks/website.yaml

Outputs:
  S3Bucket:
    Description: Information about the value
    Value: !Ref Website
    Export: 
      Name: !Ref Website