Parameters:
    Project:
      Description: Project Name | WebSite name 
      Type: String

Resources:
    website:
      Type: AWS::CloudFormation::Stack
      Properties:
          Parameters:
            Project: !Ref Project
          TemplateURL: ./stacks/website.yaml

