AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Project:
    Description: Project Name | WebSite name 
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private 
      BucketName: !Sub '${Project}-website'

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket