AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Project:
    Description: Project Name | WebSite name 
    Type: String

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private 
      BucketName: !Sub '${AWS::StackName}-${Project}-website'

Outputs:
  S3Bucket:
    Description: Information about the value
    Value: !Ref s3Bucket
    Export: 
      Name: !Ref s3Bucket